name: Run Tests and Comment

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # Grant write permission for pull requests to post comments
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev

      - name: Run pytest
        run: |
          pipenv run pytest --junitxml=test-report.xml
