name: Run Pytest

on:
  push:
    branches:
      - '*'    # or specify e.g. 'main' or ['main', 'dev']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install pipenv dependencies
        run: pipenv install --dev

      - name: Run pytest
        run: pipenv run pytest
